image: "mcr.microsoft.com/dotnet/sdk:8.0"

variables:
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
   DOTNET_CLI_TELEMETRY_OPTOUT: "true"

before_script:
   - cd MusicoStoreT4 # Ensure the working directory is set before restoring
   - dotnet restore

stages:
   - build
   - test

build:
   stage: build
   tags:
       - shared-fi
   script:
       - dotnet build --configuration Release
   rules:
       - if: $CI_MERGE_REQUEST_ID

test:
   stage: test
   tags:
       - shared-fi
   script:
       - dotnet test --configuration Release
   rules:
       - if: $CI_MERGE_REQUEST_ID