// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.SQLite.Migrations.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20241021071741_mig-1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("DataAccessLayer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2753),
                            Name = "Musical Instruments"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2758),
                            Name = "Audio Equipment"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2761),
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2767),
                            Name = "Shure"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2770),
                            Name = "Yamaha"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2773),
                            Name = "Fender"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2776),
                            Name = "Sennheiser"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2649),
                            Date = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2658),
                            Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2663),
                            Date = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2667),
                            Date = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2673),
                            Date = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2723),
                            OrderId = 1,
                            Price = 99.99m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2727),
                            OrderId = 1,
                            Price = 21.99m,
                            ProductId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2731),
                            OrderId = 2,
                            Price = 280m,
                            ProductId = 3,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2735),
                            OrderId = 3,
                            Price = 499.99m,
                            ProductId = 4,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2738),
                            OrderId = 4,
                            Price = 720.05m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2742),
                            OrderId = 5,
                            Price = 29.99m,
                            ProductId = 6,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2746),
                            OrderId = 4,
                            Price = 25.54m,
                            ProductId = 6,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2681),
                            Description = "Professional condenser microphone for studio recording",
                            ManufacturerId = 4,
                            Name = "Microphone",
                            Price = 99.99m,
                            QuantityInStock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2688),
                            Description = "Music concert DVD of popular artist",
                            ManufacturerId = 2,
                            Name = "DVD",
                            Price = 19.99m,
                            QuantityInStock = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2691),
                            Description = "Acoustic guitar with solid spruce top",
                            ManufacturerId = 1,
                            Name = "Guitar",
                            Price = 299.99m,
                            QuantityInStock = 5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2694),
                            Description = "Digital keyboard with weighted keys",
                            ManufacturerId = 3,
                            Name = "Keyboard",
                            Price = 499.99m,
                            QuantityInStock = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2698),
                            Description = "5-piece drum set with cymbals and hardware",
                            ManufacturerId = 1,
                            Name = "Drum Set",
                            Price = 699.99m,
                            QuantityInStock = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2702),
                            Description = "Adjustable microphone stand with boom arm",
                            ManufacturerId = 1,
                            Name = "Microphone Stand",
                            Price = 29.99m,
                            QuantityInStock = 20
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2705),
                            Description = "Electric bass guitar with active pickups",
                            ManufacturerId = 4,
                            Name = "Bass Guitar",
                            Price = 399.99m,
                            QuantityInStock = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2709),
                            Description = "Digital piano with weighted keys and built-in speakers",
                            ManufacturerId = 3,
                            Name = "Piano",
                            Price = 899.99m,
                            QuantityInStock = 4
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2712),
                            Description = "Full-size violin with bow and case",
                            ManufacturerId = 4,
                            Name = "Violin",
                            Price = 199.99m,
                            QuantityInStock = 6
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2716),
                            Description = "Active studio monitor speaker",
                            ManufacturerId = 4,
                            Name = "Studio Monitor",
                            Price = 149.99m,
                            QuantityInStock = 12
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2781),
                            Email = "admin@bestmusic.com",
                            Name = "Admin",
                            Role = 0
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Customer", b =>
                {
                    b.HasBaseType("DataAccessLayer.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2787),
                            Email = "johnny@samurai.nc",
                            Name = "Johnny Silverhand",
                            Role = 1,
                            Address = "Straight 68, NC",
                            City = "Night City",
                            PhoneNumber = "+04 0578 457 666",
                            PostalCode = "1020",
                            State = "The Free City of Night City"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 10, 21, 9, 17, 40, 878, DateTimeKind.Local).AddTicks(2793),
                            Email = "hluchymuzikant@seznam.cz",
                            Name = "Martin Hluchý",
                            Role = 1,
                            Address = "Botanická 69",
                            City = "Brno",
                            PhoneNumber = "+420 556 556 000",
                            PostalCode = "602 00",
                            State = "Czechia"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Order", b =>
                {
                    b.HasOne("DataAccessLayer.Models.OrderItem", null)
                        .WithMany("Comments")
                        .HasForeignKey("OrderItemId");

                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.OrderItem", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Product", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DataAccessLayer.Models.OrderItem", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
